// <auto-generated />
using EroskiApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EroskiApi.Migrations
{
    [DbContext(typeof(EroskiContext))]
    partial class EroskiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("EroskiApi.Models.Departamento", b =>
                {
                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("numero")
                        .HasColumnType("int");

                    b.HasKey("nombre");

                    b.ToTable("Eroski");
                });
#pragma warning restore 612, 618
        }
    }
}
